---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create web root directories
  file:
    path: /var/www/{{ item }}
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"
  loop: "{{ sites }}"

- name: Create index.html for each site
  template:
    src: index.html.j2
    dest: /var/www/{{ item }}/index.html
  loop: "{{ sites }}"

- name: Create nginx vhost configs
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-available/{{ item }}.conf
  loop: "{{ sites }}"
  notify: reload nginx

- name: Enable vhosts
  file:
    src: /etc/nginx/sites-available/{{ item }}.conf
    dest: /etc/nginx/sites-enabled/{{ item }}.conf
    state: link
  loop: "{{ sites }}"
  notify: reload nginx

- name: Disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
